rtt.send("echo A[B]C%d* tail")
rtt.expect("echo: A%[B%]C%%d%* tail", 500)
rtt.send("echo plain words here")
rtt.expect("echo: plain words here", 500)
rtt.send("echo MixedCASE 123 !@#")
rtt.expect("echo: MixedCASE 123 !@", 500)
rtt.send("echo")
rtt.expect("usage: echo", 500)
rtt.log("t18 PASS")
