-- query reads the pin state back from IDR (active-low)
local function query_led(name)
  rtt.send("led "..name)
  local q = rtt.expect("LED "..name.." %a+", 500)
  local st = q:match("LED "..name.." (%a+)")
  assert(st == "on" or st == "off", "FAIL: bad query text: "..tostring(st))
  return st
end
local r0 = query_led("r")
local g0 = query_led("g")
rtt.send("led g toggle")
rtt.expect("LED g toggled", 500)
local g1 = query_led("g")
assert(g1 ~= g0, "FAIL: state did not flip after toggle ("..g0.." -> "..g1..")")
rtt.send("led g toggle")
rtt.expect("LED g toggled", 500)
assert(query_led("g") == g0, "FAIL: state did not restore after second toggle")
rtt.send("led")
rtt.expect("usage: led", 500)
rtt.send("led z on")
rtt.expect("unknown LED", 500)
rtt.log("t21 PASS (r="..r0..", g: "..g0.."->"..g1.."->"..g0..")")
